/**
 * Generate `src/shell/smoke-harness-bundle.gen.ts`.
 *
 * The harness runs inside a QuickJS sandbox, which takes a string of code — so
 * the bundle has to reach the runtime as a string constant a bundler can inline
 * (Workers hosts have no filesystem to read it from). This script is the only
 * writer of that file.
 *
 * Run it via `bun run gen:smoke-harness`. It is also part of `build:shell`, so
 * anything that builds the shell gets a matching harness.
 */
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { bundleSmokeHarness } from "../src/vite";

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const target = path.join(packageRoot, "src/shell/smoke-harness-bundle.gen.ts");

const source = await bundleSmokeHarness();

const header = `/**
 * The smoke-render harness bundle, as source text. GENERATED — do not edit.
 *
 * Written by \`bun run gen:smoke-harness\` (scripts/gen-smoke-harness.ts) and
 * regenerated by this package's \`prepare\`/\`build:shell\`, so a fresh checkout
 * and every app build produce it before anything imports it.
 *
 * It is a committed placeholder rather than a build-time file read because its
 * consumers include Workers hosts, where there is no filesystem to read from at
 * runtime and every byte must be inlined by the bundler. \`null\` means "not
 * generated here" — the smoke render then FAILS OPEN (saves and logs) exactly
 * as it does when the sandbox itself is unavailable, so a partial checkout
 * never blocks a create.
 */
`;

await writeFile(
  target,
  `${header}const bundle: string | null = ${JSON.stringify(source)};\n\nexport default bundle;\n`,
  "utf-8",
);

console.log(`generated ${path.relative(packageRoot, target)} (${source.length} bytes of harness)`);
