export {
  onepasswordPlugin,
  makeOnePasswordStore,
  resolveConfiguredRef,
  ambiguityMessage,
  vaultAmbiguityMessage,
  OnePasswordAccountUpsert,
  type RefResolution,
  type OnePasswordExtension,
  type OnePasswordPluginOptions,
  type OnePasswordStore,
} from "./plugin";
export {
  OnePasswordAccount,
  OnePasswordConfig,
  SingleAccountOnePasswordConfig,
  LegacyOnePasswordConfig,
  StoredOnePasswordConfig,
  DEFAULT_ACCOUNT_ID,
  normalizeStoredConfig,
  RedactedOnePasswordAccount,
  RedactedOnePasswordConfig,
  RedactedOnePasswordAuth,
  redactAccount,
  redactConfig,
  Vault,
  AccountStatus,
  ConnectionStatus,
  OnePasswordAuth,
  DesktopAppAuth,
  ServiceAccountAuth,
} from "./types";
export { OnePasswordError } from "./errors";
export {
  makeOnePasswordService,
  makeNativeSdkService,
  makeCliService,
  OnePasswordServiceTag,
  type OnePasswordService,
  type ResolvedAuth,
} from "./service";
